// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.suzaku.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.suzaku.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.suzaku.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::CollateralFactoryAddEntityView;
#[doc(inline)]
pub use self::__buffa::view::CollateralFactoryAddEntityOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CollateralFactoryAddEntityLazyView;
#[doc(inline)]
pub use self::__buffa::view::CollateralDepositView;
#[doc(inline)]
pub use self::__buffa::view::CollateralDepositOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CollateralDepositLazyView;
#[doc(inline)]
pub use self::__buffa::view::CollateralWithdrawView;
#[doc(inline)]
pub use self::__buffa::view::CollateralWithdrawOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CollateralWithdrawLazyView;
