[package]
name = "superfluid_substreams"
version = "0.2.3"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = { workspace = true }
substreams-ethereum = { workspace = true }
buffa.workspace = true
buffa-types.workspace = true
hex = { workspace = true }
hex-literal = { workspace = true }
num-bigint = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
regex = "1"
substreams-ethereum = { workspace = true }
