// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct Burn {
        pub sender: Vec<u8>,
        pub to: Vec<u8>,
        pub amount0: substreams::scalar::BigInt,
        pub amount1: substreams::scalar::BigInt,
    }
    impl Burn {
        const TOPIC_ID: [u8; 32] = [
            93u8,
            98u8,
            74u8,
            169u8,
            193u8,
            72u8,
            21u8,
            58u8,
            179u8,
            68u8,
            108u8,
            27u8,
            21u8,
            79u8,
            102u8,
            14u8,
            231u8,
            112u8,
            30u8,
            84u8,
            159u8,
            233u8,
            182u8,
            45u8,
            171u8,
            113u8,
            113u8,
            177u8,
            200u8,
            14u8,
            111u8,
            162u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                sender: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "sender",
                )?,
                to: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "to",
                )?,
                amount0: substreams_ethereum::abi::read_uint(log.data(), 0, "amount0")?,
                amount1: substreams_ethereum::abi::read_uint(log.data(), 32, "amount1")?,
            })
        }
    }
    impl substreams_ethereum::Event for Burn {
        const NAME: &'static str = "Burn";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Mint {
        pub sender: Vec<u8>,
        pub amount0: substreams::scalar::BigInt,
        pub amount1: substreams::scalar::BigInt,
    }
    impl Mint {
        const TOPIC_ID: [u8; 32] = [
            76u8,
            32u8,
            155u8,
            95u8,
            200u8,
            173u8,
            80u8,
            117u8,
            143u8,
            19u8,
            226u8,
            225u8,
            8u8,
            139u8,
            165u8,
            106u8,
            86u8,
            13u8,
            255u8,
            105u8,
            10u8,
            28u8,
            111u8,
            239u8,
            38u8,
            57u8,
            79u8,
            76u8,
            3u8,
            130u8,
            28u8,
            79u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                sender: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "sender",
                )?,
                amount0: substreams_ethereum::abi::read_uint(log.data(), 0, "amount0")?,
                amount1: substreams_ethereum::abi::read_uint(log.data(), 32, "amount1")?,
            })
        }
    }
    impl substreams_ethereum::Event for Mint {
        const NAME: &'static str = "Mint";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Swap {
        pub sender: Vec<u8>,
        pub to: Vec<u8>,
        pub amount0_in: substreams::scalar::BigInt,
        pub amount1_in: substreams::scalar::BigInt,
        pub amount0_out: substreams::scalar::BigInt,
        pub amount1_out: substreams::scalar::BigInt,
    }
    impl Swap {
        const TOPIC_ID: [u8; 32] = [
            179u8,
            226u8,
            119u8,
            54u8,
            6u8,
            171u8,
            253u8,
            54u8,
            181u8,
            189u8,
            145u8,
            57u8,
            75u8,
            58u8,
            84u8,
            209u8,
            57u8,
            131u8,
            54u8,
            198u8,
            80u8,
            5u8,
            186u8,
            247u8,
            191u8,
            122u8,
            5u8,
            239u8,
            239u8,
            250u8,
            247u8,
            91u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 128usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 128usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 128usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                sender: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "sender",
                )?,
                to: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "to",
                )?,
                amount0_in: substreams_ethereum::abi::read_uint(
                    log.data(),
                    0,
                    "amount0_in",
                )?,
                amount1_in: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "amount1_in",
                )?,
                amount0_out: substreams_ethereum::abi::read_uint(
                    log.data(),
                    64,
                    "amount0_out",
                )?,
                amount1_out: substreams_ethereum::abi::read_uint(
                    log.data(),
                    96,
                    "amount1_out",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for Swap {
        const NAME: &'static str = "Swap";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Sync {
        pub reserve0: substreams::scalar::BigInt,
        pub reserve1: substreams::scalar::BigInt,
    }
    impl Sync {
        const TOPIC_ID: [u8; 32] = [
            207u8,
            42u8,
            165u8,
            8u8,
            118u8,
            205u8,
            251u8,
            181u8,
            65u8,
            32u8,
            111u8,
            137u8,
            175u8,
            14u8,
            231u8,
            141u8,
            68u8,
            162u8,
            171u8,
            248u8,
            211u8,
            40u8,
            227u8,
            127u8,
            164u8,
            145u8,
            127u8,
            152u8,
            33u8,
            73u8,
            132u8,
            138u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                reserve0: substreams_ethereum::abi::read_uint(
                    log.data(),
                    0,
                    "reserve0",
                )?,
                reserve1: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "reserve1",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for Sync {
        const NAME: &'static str = "Sync";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}