// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/powh3d.proto

#[derive(Clone, Debug, Default)]
pub struct EventsView<'a> {
    /// Field 1: `hourglass_on_token_purchases`
    pub hourglass_on_token_purchases: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::HourglassOnTokenPurchaseView<'a>,
    >,
    /// Field 2: `hourglass_on_token_sells`
    pub hourglass_on_token_sells: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::HourglassOnTokenSellView<'a>,
    >,
    /// Field 3: `hourglass_on_reinvestments`
    pub hourglass_on_reinvestments: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::HourglassOnReinvestmentView<'a>,
    >,
    /// Field 4: `hourglass_on_withdraws`
    pub hourglass_on_withdraws: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::HourglassOnWithdrawView<'a>,
    >,
    /// Field 5: `hourglass_transfers`
    pub hourglass_transfers: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::HourglassTransferView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for EventsView<'a> {
    type Owned = super::super::Events;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::HourglassOnTokenPurchaseView,
                    >(),
                )?;
                view.hourglass_on_token_purchases
                    .push(
                        <super::super::__buffa::view::HourglassOnTokenPurchaseView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::HourglassOnTokenSellView,
                    >(),
                )?;
                view.hourglass_on_token_sells
                    .push(
                        <super::super::__buffa::view::HourglassOnTokenSellView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::HourglassOnReinvestmentView,
                    >(),
                )?;
                view.hourglass_on_reinvestments
                    .push(
                        <super::super::__buffa::view::HourglassOnReinvestmentView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::HourglassOnWithdrawView,
                    >(),
                )?;
                view.hourglass_on_withdraws
                    .push(
                        <super::super::__buffa::view::HourglassOnWithdrawView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::HourglassTransferView,
                    >(),
                )?;
                view.hourglass_transfers
                    .push(
                        <super::super::__buffa::view::HourglassTransferView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            hourglass_on_token_purchases: self
                .hourglass_on_token_purchases
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            hourglass_on_token_sells: self
                .hourglass_on_token_sells
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            hourglass_on_reinvestments: self
                .hourglass_on_reinvestments
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            hourglass_on_withdraws: self
                .hourglass_on_withdraws
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            hourglass_transfers: self
                .hourglass_transfers
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for EventsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.hourglass_on_token_purchases {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.hourglass_on_token_sells {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.hourglass_on_reinvestments {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.hourglass_on_withdraws {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.hourglass_transfers {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.hourglass_on_token_purchases {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.hourglass_on_token_sells {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.hourglass_on_reinvestments {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.hourglass_on_withdraws {
            ::buffa::types::put_len_delimited_header(
                4u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.hourglass_transfers {
            ::buffa::types::put_len_delimited_header(
                5u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for EventsView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "powh3d.types.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.Events";
}
::buffa::impl_default_view_instance!(EventsView);
::buffa::impl_view_reborrow!(EventsView);
/** Self-contained, `'static` owned view of a `Events` message.

 Wraps [`::buffa::OwnedView`]`<`[`EventsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`EventsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct EventsOwnedView(::buffa::OwnedView<EventsView<'static>>);
impl EventsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            EventsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Events,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`EventsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &EventsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Events {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `hourglass_on_token_purchases`
    #[must_use]
    pub fn hourglass_on_token_purchases(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::HourglassOnTokenPurchaseView<'_>,
    > {
        &self.0.reborrow().hourglass_on_token_purchases
    }
    /// Field 2: `hourglass_on_token_sells`
    #[must_use]
    pub fn hourglass_on_token_sells(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::HourglassOnTokenSellView<'_>,
    > {
        &self.0.reborrow().hourglass_on_token_sells
    }
    /// Field 3: `hourglass_on_reinvestments`
    #[must_use]
    pub fn hourglass_on_reinvestments(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::HourglassOnReinvestmentView<'_>,
    > {
        &self.0.reborrow().hourglass_on_reinvestments
    }
    /// Field 4: `hourglass_on_withdraws`
    #[must_use]
    pub fn hourglass_on_withdraws(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::HourglassOnWithdrawView<'_>,
    > {
        &self.0.reborrow().hourglass_on_withdraws
    }
    /// Field 5: `hourglass_transfers`
    #[must_use]
    pub fn hourglass_transfers(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::HourglassTransferView<'_>,
    > {
        &self.0.reborrow().hourglass_transfers
    }
}
impl ::core::convert::From<::buffa::OwnedView<EventsView<'static>>> for EventsOwnedView {
    fn from(inner: ::buffa::OwnedView<EventsView<'static>>) -> Self {
        EventsOwnedView(inner)
    }
}
impl ::core::convert::From<EventsOwnedView> for ::buffa::OwnedView<EventsView<'static>> {
    fn from(wrapper: EventsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<EventsView<'static>>>
for EventsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<EventsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Events {
    type View<'a> = EventsView<'a>;
    type ViewHandle = EventsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct HourglassOnTokenPurchaseView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `customer_address`
    pub customer_address: &'a str,
    /// Field 3: `incoming_ethereum`
    pub incoming_ethereum: &'a str,
    /// Field 4: `tokens_minted`
    pub tokens_minted: &'a str,
    /// Field 5: `referred_by`
    pub referred_by: &'a str,
    /// Field 6: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 7: `log_index`
    pub log_index: u64,
    /// Field 8: `block_num`
    pub block_num: u64,
    /// Field 9: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for HourglassOnTokenPurchaseView<'a> {
    type Owned = super::super::HourglassOnTokenPurchase;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.customer_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.incoming_ethereum = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tokens_minted = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.referred_by = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HourglassOnTokenPurchase,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::HourglassOnTokenPurchase,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HourglassOnTokenPurchase {
            id: self.id.to_string(),
            customer_address: self.customer_address.to_string(),
            incoming_ethereum: self.incoming_ethereum.to_string(),
            tokens_minted: self.tokens_minted.to_string(),
            referred_by: self.referred_by.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HourglassOnTokenPurchaseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.customer_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.customer_address) as u64;
        }
        if !self.incoming_ethereum.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.incoming_ethereum) as u64;
        }
        if !self.tokens_minted.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.tokens_minted) as u64;
        }
        if !self.referred_by.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.referred_by) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.customer_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.customer_address, buf);
        }
        if !self.incoming_ethereum.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.incoming_ethereum, buf);
        }
        if !self.tokens_minted.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tokens_minted, buf);
        }
        if !self.referred_by.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.referred_by, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(9u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for HourglassOnTokenPurchaseView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "HourglassOnTokenPurchase";
    const FULL_NAME: &'static str = "powh3d.types.v1.HourglassOnTokenPurchase";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.HourglassOnTokenPurchase";
}
::buffa::impl_default_view_instance!(HourglassOnTokenPurchaseView);
::buffa::impl_view_reborrow!(HourglassOnTokenPurchaseView);
/** Self-contained, `'static` owned view of a `HourglassOnTokenPurchase` message.

 Wraps [`::buffa::OwnedView`]`<`[`HourglassOnTokenPurchaseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HourglassOnTokenPurchaseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HourglassOnTokenPurchaseOwnedView(
    ::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>>,
);
impl HourglassOnTokenPurchaseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenPurchaseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenPurchaseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HourglassOnTokenPurchase,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenPurchaseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HourglassOnTokenPurchaseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HourglassOnTokenPurchaseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::HourglassOnTokenPurchase {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `customer_address`
    #[must_use]
    pub fn customer_address(&self) -> &'_ str {
        self.0.reborrow().customer_address
    }
    /// Field 3: `incoming_ethereum`
    #[must_use]
    pub fn incoming_ethereum(&self) -> &'_ str {
        self.0.reborrow().incoming_ethereum
    }
    /// Field 4: `tokens_minted`
    #[must_use]
    pub fn tokens_minted(&self) -> &'_ str {
        self.0.reborrow().tokens_minted
    }
    /// Field 5: `referred_by`
    #[must_use]
    pub fn referred_by(&self) -> &'_ str {
        self.0.reborrow().referred_by
    }
    /// Field 6: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 7: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 8: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 9: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>>>
for HourglassOnTokenPurchaseOwnedView {
    fn from(inner: ::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>>) -> Self {
        HourglassOnTokenPurchaseOwnedView(inner)
    }
}
impl ::core::convert::From<HourglassOnTokenPurchaseOwnedView>
for ::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>> {
    fn from(wrapper: HourglassOnTokenPurchaseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>>>
for HourglassOnTokenPurchaseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HourglassOnTokenPurchaseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HourglassOnTokenPurchase {
    type View<'a> = HourglassOnTokenPurchaseView<'a>;
    type ViewHandle = HourglassOnTokenPurchaseOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct HourglassOnTokenSellView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `customer_address`
    pub customer_address: &'a str,
    /// Field 3: `tokens_burned`
    pub tokens_burned: &'a str,
    /// Field 4: `ethereum_earned`
    pub ethereum_earned: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for HourglassOnTokenSellView<'a> {
    type Owned = super::super::HourglassOnTokenSell;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.customer_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tokens_burned = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.ethereum_earned = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HourglassOnTokenSell,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::HourglassOnTokenSell,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HourglassOnTokenSell {
            id: self.id.to_string(),
            customer_address: self.customer_address.to_string(),
            tokens_burned: self.tokens_burned.to_string(),
            ethereum_earned: self.ethereum_earned.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HourglassOnTokenSellView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.customer_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.customer_address) as u64;
        }
        if !self.tokens_burned.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.tokens_burned) as u64;
        }
        if !self.ethereum_earned.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.ethereum_earned) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.customer_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.customer_address, buf);
        }
        if !self.tokens_burned.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.tokens_burned, buf);
        }
        if !self.ethereum_earned.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.ethereum_earned, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for HourglassOnTokenSellView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "HourglassOnTokenSell";
    const FULL_NAME: &'static str = "powh3d.types.v1.HourglassOnTokenSell";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.HourglassOnTokenSell";
}
::buffa::impl_default_view_instance!(HourglassOnTokenSellView);
::buffa::impl_view_reborrow!(HourglassOnTokenSellView);
/** Self-contained, `'static` owned view of a `HourglassOnTokenSell` message.

 Wraps [`::buffa::OwnedView`]`<`[`HourglassOnTokenSellView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HourglassOnTokenSellView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HourglassOnTokenSellOwnedView(
    ::buffa::OwnedView<HourglassOnTokenSellView<'static>>,
);
impl HourglassOnTokenSellOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenSellOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenSellOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HourglassOnTokenSell,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnTokenSellOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HourglassOnTokenSellView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HourglassOnTokenSellView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::HourglassOnTokenSell {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `customer_address`
    #[must_use]
    pub fn customer_address(&self) -> &'_ str {
        self.0.reborrow().customer_address
    }
    /// Field 3: `tokens_burned`
    #[must_use]
    pub fn tokens_burned(&self) -> &'_ str {
        self.0.reborrow().tokens_burned
    }
    /// Field 4: `ethereum_earned`
    #[must_use]
    pub fn ethereum_earned(&self) -> &'_ str {
        self.0.reborrow().ethereum_earned
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<HourglassOnTokenSellView<'static>>>
for HourglassOnTokenSellOwnedView {
    fn from(inner: ::buffa::OwnedView<HourglassOnTokenSellView<'static>>) -> Self {
        HourglassOnTokenSellOwnedView(inner)
    }
}
impl ::core::convert::From<HourglassOnTokenSellOwnedView>
for ::buffa::OwnedView<HourglassOnTokenSellView<'static>> {
    fn from(wrapper: HourglassOnTokenSellOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HourglassOnTokenSellView<'static>>>
for HourglassOnTokenSellOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HourglassOnTokenSellView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HourglassOnTokenSell {
    type View<'a> = HourglassOnTokenSellView<'a>;
    type ViewHandle = HourglassOnTokenSellOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct HourglassOnReinvestmentView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `customer_address`
    pub customer_address: &'a str,
    /// Field 3: `ethereum_reinvested`
    pub ethereum_reinvested: &'a str,
    /// Field 4: `tokens_minted`
    pub tokens_minted: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for HourglassOnReinvestmentView<'a> {
    type Owned = super::super::HourglassOnReinvestment;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.customer_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.ethereum_reinvested = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tokens_minted = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HourglassOnReinvestment,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::HourglassOnReinvestment,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HourglassOnReinvestment {
            id: self.id.to_string(),
            customer_address: self.customer_address.to_string(),
            ethereum_reinvested: self.ethereum_reinvested.to_string(),
            tokens_minted: self.tokens_minted.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HourglassOnReinvestmentView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.customer_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.customer_address) as u64;
        }
        if !self.ethereum_reinvested.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.ethereum_reinvested)
                        as u64;
        }
        if !self.tokens_minted.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.tokens_minted) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.customer_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.customer_address, buf);
        }
        if !self.ethereum_reinvested.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.ethereum_reinvested, buf);
        }
        if !self.tokens_minted.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tokens_minted, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for HourglassOnReinvestmentView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "HourglassOnReinvestment";
    const FULL_NAME: &'static str = "powh3d.types.v1.HourglassOnReinvestment";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.HourglassOnReinvestment";
}
::buffa::impl_default_view_instance!(HourglassOnReinvestmentView);
::buffa::impl_view_reborrow!(HourglassOnReinvestmentView);
/** Self-contained, `'static` owned view of a `HourglassOnReinvestment` message.

 Wraps [`::buffa::OwnedView`]`<`[`HourglassOnReinvestmentView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HourglassOnReinvestmentView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HourglassOnReinvestmentOwnedView(
    ::buffa::OwnedView<HourglassOnReinvestmentView<'static>>,
);
impl HourglassOnReinvestmentOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnReinvestmentOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnReinvestmentOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HourglassOnReinvestment,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnReinvestmentOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HourglassOnReinvestmentView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HourglassOnReinvestmentView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::HourglassOnReinvestment {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `customer_address`
    #[must_use]
    pub fn customer_address(&self) -> &'_ str {
        self.0.reborrow().customer_address
    }
    /// Field 3: `ethereum_reinvested`
    #[must_use]
    pub fn ethereum_reinvested(&self) -> &'_ str {
        self.0.reborrow().ethereum_reinvested
    }
    /// Field 4: `tokens_minted`
    #[must_use]
    pub fn tokens_minted(&self) -> &'_ str {
        self.0.reborrow().tokens_minted
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<HourglassOnReinvestmentView<'static>>>
for HourglassOnReinvestmentOwnedView {
    fn from(inner: ::buffa::OwnedView<HourglassOnReinvestmentView<'static>>) -> Self {
        HourglassOnReinvestmentOwnedView(inner)
    }
}
impl ::core::convert::From<HourglassOnReinvestmentOwnedView>
for ::buffa::OwnedView<HourglassOnReinvestmentView<'static>> {
    fn from(wrapper: HourglassOnReinvestmentOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HourglassOnReinvestmentView<'static>>>
for HourglassOnReinvestmentOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HourglassOnReinvestmentView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HourglassOnReinvestment {
    type View<'a> = HourglassOnReinvestmentView<'a>;
    type ViewHandle = HourglassOnReinvestmentOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct HourglassOnWithdrawView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `customer_address`
    pub customer_address: &'a str,
    /// Field 3: `ethereum_withdrawn`
    pub ethereum_withdrawn: &'a str,
    /// Field 4: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 5: `log_index`
    pub log_index: u64,
    /// Field 6: `block_num`
    pub block_num: u64,
    /// Field 7: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for HourglassOnWithdrawView<'a> {
    type Owned = super::super::HourglassOnWithdraw;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.customer_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.ethereum_withdrawn = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::HourglassOnWithdraw,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::HourglassOnWithdraw,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HourglassOnWithdraw {
            id: self.id.to_string(),
            customer_address: self.customer_address.to_string(),
            ethereum_withdrawn: self.ethereum_withdrawn.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HourglassOnWithdrawView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.customer_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.customer_address) as u64;
        }
        if !self.ethereum_withdrawn.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.ethereum_withdrawn)
                        as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.customer_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.customer_address, buf);
        }
        if !self.ethereum_withdrawn.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.ethereum_withdrawn, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for HourglassOnWithdrawView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "HourglassOnWithdraw";
    const FULL_NAME: &'static str = "powh3d.types.v1.HourglassOnWithdraw";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.HourglassOnWithdraw";
}
::buffa::impl_default_view_instance!(HourglassOnWithdrawView);
::buffa::impl_view_reborrow!(HourglassOnWithdrawView);
/** Self-contained, `'static` owned view of a `HourglassOnWithdraw` message.

 Wraps [`::buffa::OwnedView`]`<`[`HourglassOnWithdrawView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HourglassOnWithdrawView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HourglassOnWithdrawOwnedView(
    ::buffa::OwnedView<HourglassOnWithdrawView<'static>>,
);
impl HourglassOnWithdrawOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnWithdrawOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnWithdrawOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HourglassOnWithdraw,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassOnWithdrawOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HourglassOnWithdrawView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HourglassOnWithdrawView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::HourglassOnWithdraw {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `customer_address`
    #[must_use]
    pub fn customer_address(&self) -> &'_ str {
        self.0.reborrow().customer_address
    }
    /// Field 3: `ethereum_withdrawn`
    #[must_use]
    pub fn ethereum_withdrawn(&self) -> &'_ str {
        self.0.reborrow().ethereum_withdrawn
    }
    /// Field 4: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 5: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 6: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 7: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<HourglassOnWithdrawView<'static>>>
for HourglassOnWithdrawOwnedView {
    fn from(inner: ::buffa::OwnedView<HourglassOnWithdrawView<'static>>) -> Self {
        HourglassOnWithdrawOwnedView(inner)
    }
}
impl ::core::convert::From<HourglassOnWithdrawOwnedView>
for ::buffa::OwnedView<HourglassOnWithdrawView<'static>> {
    fn from(wrapper: HourglassOnWithdrawOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HourglassOnWithdrawView<'static>>>
for HourglassOnWithdrawOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HourglassOnWithdrawView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HourglassOnWithdraw {
    type View<'a> = HourglassOnWithdrawView<'a>;
    type ViewHandle = HourglassOnWithdrawOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct HourglassTransferView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `from`
    pub from: &'a str,
    /// Field 3: `to`
    pub to: &'a str,
    /// Field 4: `tokens`
    pub tokens: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for HourglassTransferView<'a> {
    type Owned = super::super::HourglassTransfer;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.from = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.to = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tokens = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::HourglassTransfer, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::HourglassTransfer, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::HourglassTransfer {
            id: self.id.to_string(),
            from: self.from.to_string(),
            to: self.to.to_string(),
            tokens: self.tokens.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for HourglassTransferView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.from.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.from) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.to) as u64;
        }
        if !self.tokens.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tokens) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.from.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.from, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.to, buf);
        }
        if !self.tokens.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tokens, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for HourglassTransferView<'a> {
    const PACKAGE: &'static str = "powh3d.types.v1";
    const NAME: &'static str = "HourglassTransfer";
    const FULL_NAME: &'static str = "powh3d.types.v1.HourglassTransfer";
    const TYPE_URL: &'static str = "type.googleapis.com/powh3d.types.v1.HourglassTransfer";
}
::buffa::impl_default_view_instance!(HourglassTransferView);
::buffa::impl_view_reborrow!(HourglassTransferView);
/** Self-contained, `'static` owned view of a `HourglassTransfer` message.

 Wraps [`::buffa::OwnedView`]`<`[`HourglassTransferView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`HourglassTransferView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct HourglassTransferOwnedView(
    ::buffa::OwnedView<HourglassTransferView<'static>>,
);
impl HourglassTransferOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassTransferOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassTransferOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::HourglassTransfer,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            HourglassTransferOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`HourglassTransferView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &HourglassTransferView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::HourglassTransfer {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `from`
    #[must_use]
    pub fn from(&self) -> &'_ str {
        self.0.reborrow().from
    }
    /// Field 3: `to`
    #[must_use]
    pub fn to(&self) -> &'_ str {
        self.0.reborrow().to
    }
    /// Field 4: `tokens`
    #[must_use]
    pub fn tokens(&self) -> &'_ str {
        self.0.reborrow().tokens
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<HourglassTransferView<'static>>>
for HourglassTransferOwnedView {
    fn from(inner: ::buffa::OwnedView<HourglassTransferView<'static>>) -> Self {
        HourglassTransferOwnedView(inner)
    }
}
impl ::core::convert::From<HourglassTransferOwnedView>
for ::buffa::OwnedView<HourglassTransferView<'static>> {
    fn from(wrapper: HourglassTransferOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<HourglassTransferView<'static>>>
for HourglassTransferOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<HourglassTransferView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::HourglassTransfer {
    type View<'a> = HourglassTransferView<'a>;
    type ViewHandle = HourglassTransferOwnedView;
}
