// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.paxos_gold.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.paxos_gold.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.paxos_gold.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::PaxgTransferView;
#[doc(inline)]
pub use self::__buffa::view::PaxgTransferOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PaxgTransferLazyView;
#[doc(inline)]
pub use self::__buffa::view::PaxgFeeCollectedView;
#[doc(inline)]
pub use self::__buffa::view::PaxgFeeCollectedOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PaxgFeeCollectedLazyView;
