// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.slisbnb.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.slisbnb.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.slisbnb.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerDepositView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerDepositOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ListaStakeManagerDepositLazyView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerRequestWithdrawView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerRequestWithdrawOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ListaStakeManagerRequestWithdrawLazyView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerClaimWithdrawalView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerClaimWithdrawalOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ListaStakeManagerClaimWithdrawalLazyView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerRewardsCompoundedView;
#[doc(inline)]
pub use self::__buffa::view::ListaStakeManagerRewardsCompoundedOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::ListaStakeManagerRewardsCompoundedLazyView;
