// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub deposit_manager_eth_receiveds: ::prost::alloc::vec::Vec<DepositManagerEthReceived>,
    #[prost(message, repeated, tag="2")]
    pub swexit_withdraw_request_createds: ::prost::alloc::vec::Vec<SwexitWithdrawRequestCreated>,
    #[prost(message, repeated, tag="3")]
    pub swexit_withdrawal_claimeds: ::prost::alloc::vec::Vec<SwexitWithdrawalClaimed>,
    #[prost(message, repeated, tag="4")]
    pub sweth_reprices: ::prost::alloc::vec::Vec<SwethReprice>,
    #[prost(message, repeated, tag="5")]
    pub sweth_node_operator_reward_percentage_updates: ::prost::alloc::vec::Vec<SwethNodeOperatorRewardPercentageUpdate>,
    #[prost(message, repeated, tag="6")]
    pub sweth_swell_treasury_reward_percentage_updates: ::prost::alloc::vec::Vec<SwethSwellTreasuryRewardPercentageUpdate>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositManagerEthReceived {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub log_index: u64,
    #[prost(uint64, tag="6")]
    pub block_num: u64,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwexitWithdrawRequestCreated {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub evt_timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub last_token_id_processed: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub rate_when_created: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub log_index: u64,
    #[prost(uint64, tag="10")]
    pub block_num: u64,
    #[prost(uint64, tag="11")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwexitWithdrawalClaimed {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub exit_claimed_eth: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub log_index: u64,
    #[prost(uint64, tag="7")]
    pub block_num: u64,
    #[prost(uint64, tag="8")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwethReprice {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub new_eth_reserves: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub new_sw_eth_to_eth_rate: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub node_operator_rewards: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub swell_treasury_rewards: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub total_eth_deposited: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub log_index: u64,
    #[prost(uint64, tag="9")]
    pub block_num: u64,
    #[prost(uint64, tag="10")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwethNodeOperatorRewardPercentageUpdate {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub old_percentage: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub new_percentage: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub log_index: u64,
    #[prost(uint64, tag="6")]
    pub block_num: u64,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwethSwellTreasuryRewardPercentageUpdate {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub old_percentage: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub new_percentage: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub log_index: u64,
    #[prost(uint64, tag="6")]
    pub block_num: u64,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
}
// @@protoc_insertion_point(module)
