// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub cgusd_investeds: ::prost::alloc::vec::Vec<CgusdInvested>,
    #[prost(message, repeated, tag = "2")]
    pub cgusd_shares_burnts: ::prost::alloc::vec::Vec<CgusdSharesBurnt>,
    #[prost(message, repeated, tag = "3")]
    pub cgusd_submitteds: ::prost::alloc::vec::Vec<CgusdSubmitted>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CgusdInvested {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub post_buffered_assets: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub post_invested_assets: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub log_index: u64,
    #[prost(uint64, tag = "7")]
    pub block_num: u64,
    #[prost(uint64, tag = "8")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CgusdSharesBurnt {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pre_rebase_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub post_rebase_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub shares_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub log_index: u64,
    #[prost(uint64, tag = "8")]
    pub block_num: u64,
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CgusdSubmitted {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub referral: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub log_index: u64,
    #[prost(uint64, tag = "7")]
    pub block_num: u64,
    #[prost(uint64, tag = "8")]
    pub timestamp: u64,
}
// @@protoc_insertion_point(module)
