// @generated by buffa-codegen. DO NOT EDIT.

include!("proto.chainlink_staking.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.chainlink_staking.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("proto.chainlink_staking.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::StakeEventView;
#[doc(inline)]
pub use self::__buffa::view::StakeEventOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::StakeEventLazyView;
#[doc(inline)]
pub use self::__buffa::view::StakeEventV1View;
#[doc(inline)]
pub use self::__buffa::view::StakeEventV1OwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::StakeEventV1LazyView;
#[doc(inline)]
pub use self::__buffa::view::RewardUpdateView;
#[doc(inline)]
pub use self::__buffa::view::RewardUpdateOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RewardUpdateLazyView;
#[doc(inline)]
pub use self::__buffa::view::RewardVaultSetView;
#[doc(inline)]
pub use self::__buffa::view::RewardVaultSetOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RewardVaultSetLazyView;
#[doc(inline)]
pub use self::__buffa::view::EventsView;
#[doc(inline)]
pub use self::__buffa::view::EventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::EventsLazyView;
