// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct PunkBidEntered {
        pub punk_index: substreams::scalar::BigInt,
        pub value: substreams::scalar::BigInt,
        pub from_address: Vec<u8>,
    }
    impl PunkBidEntered {
        const TOPIC_ID: [u8; 32] = [
            91u8,
            133u8,
            147u8,
            148u8,
            250u8,
            186u8,
            224u8,
            193u8,
            186u8,
            136u8,
            186u8,
            255u8,
            230u8,
            126u8,
            117u8,
            26u8,
            181u8,
            36u8,
            141u8,
            46u8,
            135u8,
            144u8,
            40u8,
            184u8,
            200u8,
            214u8,
            137u8,
            123u8,
            5u8,
            25u8,
            245u8,
            106u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                punk_index: substreams_ethereum::abi::read_uint(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "punk_index",
                )?,
                from_address: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "from_address",
                )?,
                value: substreams_ethereum::abi::read_uint(log.data(), 0, "value")?,
            })
        }
    }
    impl substreams_ethereum::Event for PunkBidEntered {
        const NAME: &'static str = "PunkBidEntered";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct PunkBidWithdrawn {
        pub punk_index: substreams::scalar::BigInt,
        pub value: substreams::scalar::BigInt,
        pub from_address: Vec<u8>,
    }
    impl PunkBidWithdrawn {
        const TOPIC_ID: [u8; 32] = [
            111u8,
            48u8,
            225u8,
            238u8,
            77u8,
            129u8,
            220u8,
            199u8,
            168u8,
            164u8,
            120u8,
            87u8,
            127u8,
            101u8,
            210u8,
            237u8,
            46u8,
            219u8,
            18u8,
            5u8,
            101u8,
            150u8,
            10u8,
            196u8,
            95u8,
            231u8,
            197u8,
            5u8,
            81u8,
            200u8,
            121u8,
            50u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                punk_index: substreams_ethereum::abi::read_uint(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "punk_index",
                )?,
                from_address: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "from_address",
                )?,
                value: substreams_ethereum::abi::read_uint(log.data(), 0, "value")?,
            })
        }
    }
    impl substreams_ethereum::Event for PunkBidWithdrawn {
        const NAME: &'static str = "PunkBidWithdrawn";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct PunkBought {
        pub punk_index: substreams::scalar::BigInt,
        pub value: substreams::scalar::BigInt,
        pub from_address: Vec<u8>,
        pub to_address: Vec<u8>,
    }
    impl PunkBought {
        const TOPIC_ID: [u8; 32] = [
            88u8,
            229u8,
            213u8,
            165u8,
            37u8,
            227u8,
            180u8,
            11u8,
            193u8,
            90u8,
            186u8,
            163u8,
            139u8,
            88u8,
            130u8,
            103u8,
            141u8,
            177u8,
            238u8,
            104u8,
            190u8,
            253u8,
            47u8,
            96u8,
            186u8,
            254u8,
            58u8,
            127u8,
            208u8,
            109u8,
            185u8,
            227u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 4usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 4usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 4usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                punk_index: substreams_ethereum::abi::read_uint(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "punk_index",
                )?,
                from_address: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "from_address",
                )?,
                to_address: substreams_ethereum::abi::read_address(
                    log.topic(3usize).expect("bounds already checked"),
                    0,
                    "to_address",
                )?,
                value: substreams_ethereum::abi::read_uint(log.data(), 0, "value")?,
            })
        }
    }
    impl substreams_ethereum::Event for PunkBought {
        const NAME: &'static str = "PunkBought";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct PunkNoLongerForSale {
        pub punk_index: substreams::scalar::BigInt,
    }
    impl PunkNoLongerForSale {
        const TOPIC_ID: [u8; 32] = [
            176u8,
            224u8,
            166u8,
            96u8,
            180u8,
            229u8,
            15u8,
            38u8,
            240u8,
            183u8,
            206u8,
            117u8,
            194u8,
            70u8,
            85u8,
            252u8,
            118u8,
            204u8,
            102u8,
            227u8,
            51u8,
            74u8,
            84u8,
            255u8,
            65u8,
            2u8,
            119u8,
            34u8,
            159u8,
            161u8,
            11u8,
            212u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 0usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            Ok(Self {
                punk_index: substreams_ethereum::abi::read_uint(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "punk_index",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for PunkNoLongerForSale {
        const NAME: &'static str = "PunkNoLongerForSale";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct PunkOffered {
        pub punk_index: substreams::scalar::BigInt,
        pub min_value: substreams::scalar::BigInt,
        pub to_address: Vec<u8>,
    }
    impl PunkOffered {
        const TOPIC_ID: [u8; 32] = [
            60u8,
            123u8,
            104u8,
            45u8,
            93u8,
            169u8,
            128u8,
            1u8,
            169u8,
            184u8,
            203u8,
            218u8,
            108u8,
            100u8,
            125u8,
            44u8,
            99u8,
            214u8,
            152u8,
            164u8,
            24u8,
            79u8,
            209u8,
            213u8,
            94u8,
            44u8,
            231u8,
            182u8,
            111u8,
            93u8,
            33u8,
            235u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                punk_index: substreams_ethereum::abi::read_uint(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "punk_index",
                )?,
                to_address: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "to_address",
                )?,
                min_value: substreams_ethereum::abi::read_uint(
                    log.data(),
                    0,
                    "min_value",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for PunkOffered {
        const NAME: &'static str = "PunkOffered";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}