// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/cbeth.proto

#[derive(Clone, Debug, Default)]
pub struct EventsView<'a> {
    /// Field 1: `mints`
    pub mints: ::buffa::RepeatedView<'a, super::super::__buffa::view::MintView<'a>>,
    /// Field 2: `burns`
    pub burns: ::buffa::RepeatedView<'a, super::super::__buffa::view::BurnView<'a>>,
    /// Field 3: `exchange_rate_updates`
    pub exchange_rate_updates: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::ExchangeRateUpdatedView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for EventsView<'a> {
    type Owned = super::super::Events;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::MintView>(),
                )?;
                view.mints
                    .push(
                        <super::super::__buffa::view::MintView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::BurnView>(),
                )?;
                view.burns
                    .push(
                        <super::super::__buffa::view::BurnView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::ExchangeRateUpdatedView,
                    >(),
                )?;
                view.exchange_rate_updates
                    .push(
                        <super::super::__buffa::view::ExchangeRateUpdatedView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            mints: self
                .mints
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            burns: self
                .burns
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            exchange_rate_updates: self
                .exchange_rate_updates
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for EventsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.mints {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.burns {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.exchange_rate_updates {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.mints {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.burns {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.exchange_rate_updates {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for EventsView<'a> {
    const PACKAGE: &'static str = "cbeth.types.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "cbeth.types.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/cbeth.types.v1.Events";
}
::buffa::impl_default_view_instance!(EventsView);
::buffa::impl_view_reborrow!(EventsView);
/** Self-contained, `'static` owned view of a `Events` message.

 Wraps [`::buffa::OwnedView`]`<`[`EventsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`EventsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct EventsOwnedView(::buffa::OwnedView<EventsView<'static>>);
impl EventsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            EventsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Events,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`EventsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &EventsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Events {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `mints`
    #[must_use]
    pub fn mints(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::MintView<'_>> {
        &self.0.reborrow().mints
    }
    /// Field 2: `burns`
    #[must_use]
    pub fn burns(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::BurnView<'_>> {
        &self.0.reborrow().burns
    }
    /// Field 3: `exchange_rate_updates`
    #[must_use]
    pub fn exchange_rate_updates(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::ExchangeRateUpdatedView<'_>,
    > {
        &self.0.reborrow().exchange_rate_updates
    }
}
impl ::core::convert::From<::buffa::OwnedView<EventsView<'static>>> for EventsOwnedView {
    fn from(inner: ::buffa::OwnedView<EventsView<'static>>) -> Self {
        EventsOwnedView(inner)
    }
}
impl ::core::convert::From<EventsOwnedView> for ::buffa::OwnedView<EventsView<'static>> {
    fn from(wrapper: EventsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<EventsView<'static>>>
for EventsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<EventsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Events {
    type View<'a> = EventsView<'a>;
    type ViewHandle = EventsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct MintView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `minter`
    pub minter: &'a str,
    /// Field 3: `to`
    pub to: &'a str,
    /// Field 4: `amount`
    pub amount: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for MintView<'a> {
    type Owned = super::super::Mint;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.minter = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.to = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Mint, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Mint, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Mint {
            id: self.id.to_string(),
            minter: self.minter.to_string(),
            to: self.to.to_string(),
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for MintView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.minter.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.minter) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.to) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.minter.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.minter, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.to, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for MintView<'a> {
    const PACKAGE: &'static str = "cbeth.types.v1";
    const NAME: &'static str = "Mint";
    const FULL_NAME: &'static str = "cbeth.types.v1.Mint";
    const TYPE_URL: &'static str = "type.googleapis.com/cbeth.types.v1.Mint";
}
::buffa::impl_default_view_instance!(MintView);
::buffa::impl_view_reborrow!(MintView);
/** Self-contained, `'static` owned view of a `Mint` message.

 Wraps [`::buffa::OwnedView`]`<`[`MintView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`MintView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct MintOwnedView(::buffa::OwnedView<MintView<'static>>);
impl MintOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(MintOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            MintOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Mint,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(MintOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`MintView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &MintView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Mint {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `minter`
    #[must_use]
    pub fn minter(&self) -> &'_ str {
        self.0.reborrow().minter
    }
    /// Field 3: `to`
    #[must_use]
    pub fn to(&self) -> &'_ str {
        self.0.reborrow().to
    }
    /// Field 4: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<MintView<'static>>> for MintOwnedView {
    fn from(inner: ::buffa::OwnedView<MintView<'static>>) -> Self {
        MintOwnedView(inner)
    }
}
impl ::core::convert::From<MintOwnedView> for ::buffa::OwnedView<MintView<'static>> {
    fn from(wrapper: MintOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<MintView<'static>>> for MintOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<MintView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Mint {
    type View<'a> = MintView<'a>;
    type ViewHandle = MintOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct BurnView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `burner`
    pub burner: &'a str,
    /// Field 3: `amount`
    pub amount: &'a str,
    /// Field 4: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 5: `log_index`
    pub log_index: u64,
    /// Field 6: `block_num`
    pub block_num: u64,
    /// Field 7: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for BurnView<'a> {
    type Owned = super::super::Burn;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.burner = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Burn, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Burn, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Burn {
            id: self.id.to_string(),
            burner: self.burner.to_string(),
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BurnView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.burner.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.burner) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.burner.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.burner, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BurnView<'a> {
    const PACKAGE: &'static str = "cbeth.types.v1";
    const NAME: &'static str = "Burn";
    const FULL_NAME: &'static str = "cbeth.types.v1.Burn";
    const TYPE_URL: &'static str = "type.googleapis.com/cbeth.types.v1.Burn";
}
::buffa::impl_default_view_instance!(BurnView);
::buffa::impl_view_reborrow!(BurnView);
/** Self-contained, `'static` owned view of a `Burn` message.

 Wraps [`::buffa::OwnedView`]`<`[`BurnView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BurnView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BurnOwnedView(::buffa::OwnedView<BurnView<'static>>);
impl BurnOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(BurnOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BurnOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Burn,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(BurnOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`BurnView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BurnView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Burn {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `burner`
    #[must_use]
    pub fn burner(&self) -> &'_ str {
        self.0.reborrow().burner
    }
    /// Field 3: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 4: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 5: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 6: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 7: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<BurnView<'static>>> for BurnOwnedView {
    fn from(inner: ::buffa::OwnedView<BurnView<'static>>) -> Self {
        BurnOwnedView(inner)
    }
}
impl ::core::convert::From<BurnOwnedView> for ::buffa::OwnedView<BurnView<'static>> {
    fn from(wrapper: BurnOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BurnView<'static>>> for BurnOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BurnView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Burn {
    type View<'a> = BurnView<'a>;
    type ViewHandle = BurnOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct ExchangeRateUpdatedView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `oracle`
    pub oracle: &'a str,
    /// Field 3: `new_exchange_rate`
    pub new_exchange_rate: &'a str,
    /// Field 4: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 5: `log_index`
    pub log_index: u64,
    /// Field 6: `block_num`
    pub block_num: u64,
    /// Field 7: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for ExchangeRateUpdatedView<'a> {
    type Owned = super::super::ExchangeRateUpdated;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.oracle = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.new_exchange_rate = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::ExchangeRateUpdated,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::ExchangeRateUpdated,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::ExchangeRateUpdated {
            id: self.id.to_string(),
            oracle: self.oracle.to_string(),
            new_exchange_rate: self.new_exchange_rate.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for ExchangeRateUpdatedView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.oracle.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.oracle) as u64;
        }
        if !self.new_exchange_rate.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.new_exchange_rate) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.oracle.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.oracle, buf);
        }
        if !self.new_exchange_rate.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.new_exchange_rate, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for ExchangeRateUpdatedView<'a> {
    const PACKAGE: &'static str = "cbeth.types.v1";
    const NAME: &'static str = "ExchangeRateUpdated";
    const FULL_NAME: &'static str = "cbeth.types.v1.ExchangeRateUpdated";
    const TYPE_URL: &'static str = "type.googleapis.com/cbeth.types.v1.ExchangeRateUpdated";
}
::buffa::impl_default_view_instance!(ExchangeRateUpdatedView);
::buffa::impl_view_reborrow!(ExchangeRateUpdatedView);
/** Self-contained, `'static` owned view of a `ExchangeRateUpdated` message.

 Wraps [`::buffa::OwnedView`]`<`[`ExchangeRateUpdatedView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`ExchangeRateUpdatedView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct ExchangeRateUpdatedOwnedView(
    ::buffa::OwnedView<ExchangeRateUpdatedView<'static>>,
);
impl ExchangeRateUpdatedOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ExchangeRateUpdatedOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ExchangeRateUpdatedOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::ExchangeRateUpdated,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            ExchangeRateUpdatedOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`ExchangeRateUpdatedView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &ExchangeRateUpdatedView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::ExchangeRateUpdated {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `oracle`
    #[must_use]
    pub fn oracle(&self) -> &'_ str {
        self.0.reborrow().oracle
    }
    /// Field 3: `new_exchange_rate`
    #[must_use]
    pub fn new_exchange_rate(&self) -> &'_ str {
        self.0.reborrow().new_exchange_rate
    }
    /// Field 4: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 5: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 6: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 7: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<ExchangeRateUpdatedView<'static>>>
for ExchangeRateUpdatedOwnedView {
    fn from(inner: ::buffa::OwnedView<ExchangeRateUpdatedView<'static>>) -> Self {
        ExchangeRateUpdatedOwnedView(inner)
    }
}
impl ::core::convert::From<ExchangeRateUpdatedOwnedView>
for ::buffa::OwnedView<ExchangeRateUpdatedView<'static>> {
    fn from(wrapper: ExchangeRateUpdatedOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<ExchangeRateUpdatedView<'static>>>
for ExchangeRateUpdatedOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<ExchangeRateUpdatedView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::ExchangeRateUpdated {
    type View<'a> = ExchangeRateUpdatedView<'a>;
    type ViewHandle = ExchangeRateUpdatedOwnedView;
}
