// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/liquid_collective.proto

#[derive(Clone, Debug, Default)]
pub struct EventsView<'a> {
    /// Field 1: `lseth_pulled_el_feess`
    pub lseth_pulled_el_feess: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::LsethPulledElFeesView<'a>,
    >,
    /// Field 2: `lseth_user_deposits`
    pub lseth_user_deposits: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::LsethUserDepositView<'a>,
    >,
    /// Field 3: `redeem_manager_requested_redeems`
    pub redeem_manager_requested_redeems: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RedeemManagerRequestedRedeemView<'a>,
    >,
    /// Field 4: `redeem_manager_claimed_redeem_requests`
    pub redeem_manager_claimed_redeem_requests: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RedeemManagerClaimedRedeemRequestView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for EventsView<'a> {
    type Owned = super::super::Events;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::LsethPulledElFeesView,
                    >(),
                )?;
                view.lseth_pulled_el_feess
                    .push(
                        <super::super::__buffa::view::LsethPulledElFeesView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::LsethUserDepositView,
                    >(),
                )?;
                view.lseth_user_deposits
                    .push(
                        <super::super::__buffa::view::LsethUserDepositView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::RedeemManagerRequestedRedeemView,
                    >(),
                )?;
                view.redeem_manager_requested_redeems
                    .push(
                        <super::super::__buffa::view::RedeemManagerRequestedRedeemView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::RedeemManagerClaimedRedeemRequestView,
                    >(),
                )?;
                view.redeem_manager_claimed_redeem_requests
                    .push(
                        <super::super::__buffa::view::RedeemManagerClaimedRedeemRequestView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            lseth_pulled_el_feess: self
                .lseth_pulled_el_feess
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            lseth_user_deposits: self
                .lseth_user_deposits
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            redeem_manager_requested_redeems: self
                .redeem_manager_requested_redeems
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            redeem_manager_claimed_redeem_requests: self
                .redeem_manager_claimed_redeem_requests
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for EventsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.lseth_pulled_el_feess {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.lseth_user_deposits {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.redeem_manager_requested_redeems {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.redeem_manager_claimed_redeem_requests {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.lseth_pulled_el_feess {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.lseth_user_deposits {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.redeem_manager_requested_redeems {
            ::buffa::types::put_len_delimited_header(
                3u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.redeem_manager_claimed_redeem_requests {
            ::buffa::types::put_len_delimited_header(
                4u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for EventsView<'a> {
    const PACKAGE: &'static str = "liquid_collective.types.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "liquid_collective.types.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/liquid_collective.types.v1.Events";
}
::buffa::impl_default_view_instance!(EventsView);
::buffa::impl_view_reborrow!(EventsView);
/** Self-contained, `'static` owned view of a `Events` message.

 Wraps [`::buffa::OwnedView`]`<`[`EventsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`EventsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct EventsOwnedView(::buffa::OwnedView<EventsView<'static>>);
impl EventsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            EventsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Events,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`EventsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &EventsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Events {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `lseth_pulled_el_feess`
    #[must_use]
    pub fn lseth_pulled_el_feess(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::LsethPulledElFeesView<'_>,
    > {
        &self.0.reborrow().lseth_pulled_el_feess
    }
    /// Field 2: `lseth_user_deposits`
    #[must_use]
    pub fn lseth_user_deposits(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::LsethUserDepositView<'_>,
    > {
        &self.0.reborrow().lseth_user_deposits
    }
    /// Field 3: `redeem_manager_requested_redeems`
    #[must_use]
    pub fn redeem_manager_requested_redeems(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RedeemManagerRequestedRedeemView<'_>,
    > {
        &self.0.reborrow().redeem_manager_requested_redeems
    }
    /// Field 4: `redeem_manager_claimed_redeem_requests`
    #[must_use]
    pub fn redeem_manager_claimed_redeem_requests(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RedeemManagerClaimedRedeemRequestView<'_>,
    > {
        &self.0.reborrow().redeem_manager_claimed_redeem_requests
    }
}
impl ::core::convert::From<::buffa::OwnedView<EventsView<'static>>> for EventsOwnedView {
    fn from(inner: ::buffa::OwnedView<EventsView<'static>>) -> Self {
        EventsOwnedView(inner)
    }
}
impl ::core::convert::From<EventsOwnedView> for ::buffa::OwnedView<EventsView<'static>> {
    fn from(wrapper: EventsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<EventsView<'static>>>
for EventsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<EventsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Events {
    type View<'a> = EventsView<'a>;
    type ViewHandle = EventsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct LsethPulledElFeesView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `amount`
    pub amount: &'a str,
    /// Field 3: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 4: `log_index`
    pub log_index: u64,
    /// Field 5: `block_num`
    pub block_num: u64,
    /// Field 6: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for LsethPulledElFeesView<'a> {
    type Owned = super::super::LsethPulledElFees;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::LsethPulledElFees, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::LsethPulledElFees, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::LsethPulledElFees {
            id: self.id.to_string(),
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for LsethPulledElFeesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(4u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(5u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for LsethPulledElFeesView<'a> {
    const PACKAGE: &'static str = "liquid_collective.types.v1";
    const NAME: &'static str = "LsethPulledElFees";
    const FULL_NAME: &'static str = "liquid_collective.types.v1.LsethPulledElFees";
    const TYPE_URL: &'static str = "type.googleapis.com/liquid_collective.types.v1.LsethPulledElFees";
}
::buffa::impl_default_view_instance!(LsethPulledElFeesView);
::buffa::impl_view_reborrow!(LsethPulledElFeesView);
/** Self-contained, `'static` owned view of a `LsethPulledElFees` message.

 Wraps [`::buffa::OwnedView`]`<`[`LsethPulledElFeesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`LsethPulledElFeesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct LsethPulledElFeesOwnedView(
    ::buffa::OwnedView<LsethPulledElFeesView<'static>>,
);
impl LsethPulledElFeesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethPulledElFeesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethPulledElFeesOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::LsethPulledElFees,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethPulledElFeesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`LsethPulledElFeesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &LsethPulledElFeesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::LsethPulledElFees {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 3: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 4: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 5: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 6: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<LsethPulledElFeesView<'static>>>
for LsethPulledElFeesOwnedView {
    fn from(inner: ::buffa::OwnedView<LsethPulledElFeesView<'static>>) -> Self {
        LsethPulledElFeesOwnedView(inner)
    }
}
impl ::core::convert::From<LsethPulledElFeesOwnedView>
for ::buffa::OwnedView<LsethPulledElFeesView<'static>> {
    fn from(wrapper: LsethPulledElFeesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<LsethPulledElFeesView<'static>>>
for LsethPulledElFeesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<LsethPulledElFeesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::LsethPulledElFees {
    type View<'a> = LsethPulledElFeesView<'a>;
    type ViewHandle = LsethPulledElFeesOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct LsethUserDepositView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `depositor`
    pub depositor: &'a str,
    /// Field 3: `recipient`
    pub recipient: &'a str,
    /// Field 4: `amount`
    pub amount: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for LsethUserDepositView<'a> {
    type Owned = super::super::LsethUserDeposit;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.depositor = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.recipient = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::LsethUserDeposit, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::LsethUserDeposit, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::LsethUserDeposit {
            id: self.id.to_string(),
            depositor: self.depositor.to_string(),
            recipient: self.recipient.to_string(),
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for LsethUserDepositView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.depositor.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.depositor) as u64;
        }
        if !self.recipient.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.recipient) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.depositor.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.depositor, buf);
        }
        if !self.recipient.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.recipient, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for LsethUserDepositView<'a> {
    const PACKAGE: &'static str = "liquid_collective.types.v1";
    const NAME: &'static str = "LsethUserDeposit";
    const FULL_NAME: &'static str = "liquid_collective.types.v1.LsethUserDeposit";
    const TYPE_URL: &'static str = "type.googleapis.com/liquid_collective.types.v1.LsethUserDeposit";
}
::buffa::impl_default_view_instance!(LsethUserDepositView);
::buffa::impl_view_reborrow!(LsethUserDepositView);
/** Self-contained, `'static` owned view of a `LsethUserDeposit` message.

 Wraps [`::buffa::OwnedView`]`<`[`LsethUserDepositView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`LsethUserDepositView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct LsethUserDepositOwnedView(::buffa::OwnedView<LsethUserDepositView<'static>>);
impl LsethUserDepositOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethUserDepositOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethUserDepositOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::LsethUserDeposit,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            LsethUserDepositOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`LsethUserDepositView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &LsethUserDepositView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::LsethUserDeposit {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `depositor`
    #[must_use]
    pub fn depositor(&self) -> &'_ str {
        self.0.reborrow().depositor
    }
    /// Field 3: `recipient`
    #[must_use]
    pub fn recipient(&self) -> &'_ str {
        self.0.reborrow().recipient
    }
    /// Field 4: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<LsethUserDepositView<'static>>>
for LsethUserDepositOwnedView {
    fn from(inner: ::buffa::OwnedView<LsethUserDepositView<'static>>) -> Self {
        LsethUserDepositOwnedView(inner)
    }
}
impl ::core::convert::From<LsethUserDepositOwnedView>
for ::buffa::OwnedView<LsethUserDepositView<'static>> {
    fn from(wrapper: LsethUserDepositOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<LsethUserDepositView<'static>>>
for LsethUserDepositOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<LsethUserDepositView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::LsethUserDeposit {
    type View<'a> = LsethUserDepositView<'a>;
    type ViewHandle = LsethUserDepositOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RedeemManagerRequestedRedeemView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `owner`
    pub owner: &'a str,
    /// Field 3: `height`
    pub height: &'a str,
    /// Field 4: `amount`
    pub amount: &'a str,
    /// Field 5: `max_redeemable_eth`
    pub max_redeemable_eth: &'a str,
    /// Field 6: `evt_id`
    pub evt_id: &'a str,
    /// Field 7: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 8: `log_index`
    pub log_index: u64,
    /// Field 9: `block_num`
    pub block_num: u64,
    /// Field 10: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for RedeemManagerRequestedRedeemView<'a> {
    type Owned = super::super::RedeemManagerRequestedRedeem;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.owner = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.height = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.max_redeemable_eth = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.evt_id = ::buffa::types::borrow_str(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RedeemManagerRequestedRedeem,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RedeemManagerRequestedRedeem,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RedeemManagerRequestedRedeem {
            id: self.id.to_string(),
            owner: self.owner.to_string(),
            height: self.height.to_string(),
            amount: self.amount.to_string(),
            max_redeemable_eth: self.max_redeemable_eth.to_string(),
            evt_id: self.evt_id.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RedeemManagerRequestedRedeemView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.owner.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.owner) as u64;
        }
        if !self.height.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.height) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.max_redeemable_eth.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.max_redeemable_eth)
                        as u64;
        }
        if !self.evt_id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.evt_id) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.owner.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.owner, buf);
        }
        if !self.height.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.height, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount, buf);
        }
        if !self.max_redeemable_eth.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.max_redeemable_eth, buf);
        }
        if !self.evt_id.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.evt_id, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(7u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(9u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(10u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RedeemManagerRequestedRedeemView<'a> {
    const PACKAGE: &'static str = "liquid_collective.types.v1";
    const NAME: &'static str = "RedeemManagerRequestedRedeem";
    const FULL_NAME: &'static str = "liquid_collective.types.v1.RedeemManagerRequestedRedeem";
    const TYPE_URL: &'static str = "type.googleapis.com/liquid_collective.types.v1.RedeemManagerRequestedRedeem";
}
::buffa::impl_default_view_instance!(RedeemManagerRequestedRedeemView);
::buffa::impl_view_reborrow!(RedeemManagerRequestedRedeemView);
/** Self-contained, `'static` owned view of a `RedeemManagerRequestedRedeem` message.

 Wraps [`::buffa::OwnedView`]`<`[`RedeemManagerRequestedRedeemView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RedeemManagerRequestedRedeemView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RedeemManagerRequestedRedeemOwnedView(
    ::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>>,
);
impl RedeemManagerRequestedRedeemOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerRequestedRedeemOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerRequestedRedeemOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RedeemManagerRequestedRedeem,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerRequestedRedeemOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RedeemManagerRequestedRedeemView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RedeemManagerRequestedRedeemView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RedeemManagerRequestedRedeem {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `owner`
    #[must_use]
    pub fn owner(&self) -> &'_ str {
        self.0.reborrow().owner
    }
    /// Field 3: `height`
    #[must_use]
    pub fn height(&self) -> &'_ str {
        self.0.reborrow().height
    }
    /// Field 4: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 5: `max_redeemable_eth`
    #[must_use]
    pub fn max_redeemable_eth(&self) -> &'_ str {
        self.0.reborrow().max_redeemable_eth
    }
    /// Field 6: `evt_id`
    #[must_use]
    pub fn evt_id(&self) -> &'_ str {
        self.0.reborrow().evt_id
    }
    /// Field 7: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 8: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 9: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 10: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>>>
for RedeemManagerRequestedRedeemOwnedView {
    fn from(
        inner: ::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>>,
    ) -> Self {
        RedeemManagerRequestedRedeemOwnedView(inner)
    }
}
impl ::core::convert::From<RedeemManagerRequestedRedeemOwnedView>
for ::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>> {
    fn from(wrapper: RedeemManagerRequestedRedeemOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<
    ::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>>,
> for RedeemManagerRequestedRedeemOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RedeemManagerRequestedRedeemView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RedeemManagerRequestedRedeem {
    type View<'a> = RedeemManagerRequestedRedeemView<'a>;
    type ViewHandle = RedeemManagerRequestedRedeemOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RedeemManagerClaimedRedeemRequestView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `redeem_request_id`
    pub redeem_request_id: &'a str,
    /// Field 3: `recipient`
    pub recipient: &'a str,
    /// Field 4: `eth_amount`
    pub eth_amount: &'a str,
    /// Field 5: `ls_eth_amount`
    pub ls_eth_amount: &'a str,
    /// Field 6: `remaining_ls_eth_amount`
    pub remaining_ls_eth_amount: &'a str,
    /// Field 7: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 8: `log_index`
    pub log_index: u64,
    /// Field 9: `block_num`
    pub block_num: u64,
    /// Field 10: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for RedeemManagerClaimedRedeemRequestView<'a> {
    type Owned = super::super::RedeemManagerClaimedRedeemRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.redeem_request_id = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.recipient = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.eth_amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.ls_eth_amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.remaining_ls_eth_amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RedeemManagerClaimedRedeemRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RedeemManagerClaimedRedeemRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RedeemManagerClaimedRedeemRequest {
            id: self.id.to_string(),
            redeem_request_id: self.redeem_request_id.to_string(),
            recipient: self.recipient.to_string(),
            eth_amount: self.eth_amount.to_string(),
            ls_eth_amount: self.ls_eth_amount.to_string(),
            remaining_ls_eth_amount: self.remaining_ls_eth_amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RedeemManagerClaimedRedeemRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.redeem_request_id.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.redeem_request_id) as u64;
        }
        if !self.recipient.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.recipient) as u64;
        }
        if !self.eth_amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.eth_amount) as u64;
        }
        if !self.ls_eth_amount.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.ls_eth_amount) as u64;
        }
        if !self.remaining_ls_eth_amount.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.remaining_ls_eth_amount)
                        as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.redeem_request_id.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.redeem_request_id, buf);
        }
        if !self.recipient.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.recipient, buf);
        }
        if !self.eth_amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.eth_amount, buf);
        }
        if !self.ls_eth_amount.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.ls_eth_amount, buf);
        }
        if !self.remaining_ls_eth_amount.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.remaining_ls_eth_amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(7u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(9u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(10u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RedeemManagerClaimedRedeemRequestView<'a> {
    const PACKAGE: &'static str = "liquid_collective.types.v1";
    const NAME: &'static str = "RedeemManagerClaimedRedeemRequest";
    const FULL_NAME: &'static str = "liquid_collective.types.v1.RedeemManagerClaimedRedeemRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/liquid_collective.types.v1.RedeemManagerClaimedRedeemRequest";
}
::buffa::impl_default_view_instance!(RedeemManagerClaimedRedeemRequestView);
::buffa::impl_view_reborrow!(RedeemManagerClaimedRedeemRequestView);
/** Self-contained, `'static` owned view of a `RedeemManagerClaimedRedeemRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`RedeemManagerClaimedRedeemRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RedeemManagerClaimedRedeemRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RedeemManagerClaimedRedeemRequestOwnedView(
    ::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>>,
);
impl RedeemManagerClaimedRedeemRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerClaimedRedeemRequestOwnedView(
                ::buffa::OwnedView::decode(bytes)?,
            ),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerClaimedRedeemRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RedeemManagerClaimedRedeemRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RedeemManagerClaimedRedeemRequestOwnedView(
                ::buffa::OwnedView::from_owned(msg)?,
            ),
        )
    }
    /// Borrow the full [`RedeemManagerClaimedRedeemRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RedeemManagerClaimedRedeemRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RedeemManagerClaimedRedeemRequest {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `redeem_request_id`
    #[must_use]
    pub fn redeem_request_id(&self) -> &'_ str {
        self.0.reborrow().redeem_request_id
    }
    /// Field 3: `recipient`
    #[must_use]
    pub fn recipient(&self) -> &'_ str {
        self.0.reborrow().recipient
    }
    /// Field 4: `eth_amount`
    #[must_use]
    pub fn eth_amount(&self) -> &'_ str {
        self.0.reborrow().eth_amount
    }
    /// Field 5: `ls_eth_amount`
    #[must_use]
    pub fn ls_eth_amount(&self) -> &'_ str {
        self.0.reborrow().ls_eth_amount
    }
    /// Field 6: `remaining_ls_eth_amount`
    #[must_use]
    pub fn remaining_ls_eth_amount(&self) -> &'_ str {
        self.0.reborrow().remaining_ls_eth_amount
    }
    /// Field 7: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 8: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 9: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 10: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<
    ::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>>,
> for RedeemManagerClaimedRedeemRequestOwnedView {
    fn from(
        inner: ::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>>,
    ) -> Self {
        RedeemManagerClaimedRedeemRequestOwnedView(inner)
    }
}
impl ::core::convert::From<RedeemManagerClaimedRedeemRequestOwnedView>
for ::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>> {
    fn from(wrapper: RedeemManagerClaimedRedeemRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<
    ::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>>,
> for RedeemManagerClaimedRedeemRequestOwnedView {
    fn as_ref(
        &self,
    ) -> &::buffa::OwnedView<RedeemManagerClaimedRedeemRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RedeemManagerClaimedRedeemRequest {
    type View<'a> = RedeemManagerClaimedRedeemRequestView<'a>;
    type ViewHandle = RedeemManagerClaimedRedeemRequestOwnedView;
}
