// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/matrixdock.proto

#[derive(Clone, PartialEq, Default)]
pub struct Events {
    /// Field 1: `stbt_transfers`
    pub stbt_transfers: ::buffa::alloc::vec::Vec<StbtTransfer>,
    /// Field 2: `stbt_interests_distributeds`
    pub stbt_interests_distributeds: ::buffa::alloc::vec::Vec<StbtInterestsDistributed>,
}
impl ::core::fmt::Debug for Events {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Events")
            .field("stbt_transfers", &self.stbt_transfers)
            .field("stbt_interests_distributeds", &self.stbt_interests_distributeds)
            .finish()
    }
}
impl Events {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.Events";
}
::buffa::impl_default_instance!(Events);
impl ::buffa::MessageName for Events {
    const PACKAGE: &'static str = "matrixdock.types.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "matrixdock.types.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.Events";
}
impl ::buffa::Message for Events {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.stbt_transfers {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.stbt_interests_distributeds {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.stbt_transfers {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.stbt_interests_distributeds {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.stbt_transfers.push(elem);
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.stbt_interests_distributeds.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.stbt_transfers.clear();
        self.stbt_interests_distributeds.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct StbtTransfer {
    /// Field 1: `id`
    pub id: ::buffa::alloc::string::String,
    /// Field 2: `from`
    pub from: ::buffa::alloc::string::String,
    /// Field 3: `to`
    pub to: ::buffa::alloc::string::String,
    /// Field 4: `value`
    pub value: ::buffa::alloc::string::String,
    /// Field 5: `tx_hash`
    pub tx_hash: ::buffa::alloc::string::String,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl ::core::fmt::Debug for StbtTransfer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("StbtTransfer")
            .field("id", &self.id)
            .field("from", &self.from)
            .field("to", &self.to)
            .field("value", &self.value)
            .field("tx_hash", &self.tx_hash)
            .field("log_index", &self.log_index)
            .field("block_num", &self.block_num)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl StbtTransfer {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.StbtTransfer";
}
::buffa::impl_default_instance!(StbtTransfer);
impl ::buffa::MessageName for StbtTransfer {
    const PACKAGE: &'static str = "matrixdock.types.v1";
    const NAME: &'static str = "StbtTransfer";
    const FULL_NAME: &'static str = "matrixdock.types.v1.StbtTransfer";
    const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.StbtTransfer";
}
impl ::buffa::Message for StbtTransfer {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.from.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.from) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.to) as u64;
        }
        if !self.value.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.value) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.from.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.from, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.to, buf);
        }
        if !self.value.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.value, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.id, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.from, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.to, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.value, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.tx_hash, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.log_index = ::buffa::types::decode_uint64(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.block_num = ::buffa::types::decode_uint64(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_uint64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.id.clear();
        self.from.clear();
        self.to.clear();
        self.value.clear();
        self.tx_hash.clear();
        self.log_index = 0u64;
        self.block_num = 0u64;
        self.timestamp = 0u64;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct StbtInterestsDistributed {
    /// Field 1: `id`
    pub id: ::buffa::alloc::string::String,
    /// Field 2: `interest`
    pub interest: ::buffa::alloc::string::String,
    /// Field 3: `new_total_supply`
    pub new_total_supply: ::buffa::alloc::string::String,
    /// Field 4: `interest_from_time`
    pub interest_from_time: ::buffa::alloc::string::String,
    /// Field 5: `interest_to_time`
    pub interest_to_time: ::buffa::alloc::string::String,
    /// Field 6: `tx_hash`
    pub tx_hash: ::buffa::alloc::string::String,
    /// Field 7: `log_index`
    pub log_index: u64,
    /// Field 8: `block_num`
    pub block_num: u64,
    /// Field 9: `timestamp`
    pub timestamp: u64,
}
impl ::core::fmt::Debug for StbtInterestsDistributed {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("StbtInterestsDistributed")
            .field("id", &self.id)
            .field("interest", &self.interest)
            .field("new_total_supply", &self.new_total_supply)
            .field("interest_from_time", &self.interest_from_time)
            .field("interest_to_time", &self.interest_to_time)
            .field("tx_hash", &self.tx_hash)
            .field("log_index", &self.log_index)
            .field("block_num", &self.block_num)
            .field("timestamp", &self.timestamp)
            .finish()
    }
}
impl StbtInterestsDistributed {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.StbtInterestsDistributed";
}
::buffa::impl_default_instance!(StbtInterestsDistributed);
impl ::buffa::MessageName for StbtInterestsDistributed {
    const PACKAGE: &'static str = "matrixdock.types.v1";
    const NAME: &'static str = "StbtInterestsDistributed";
    const FULL_NAME: &'static str = "matrixdock.types.v1.StbtInterestsDistributed";
    const TYPE_URL: &'static str = "type.googleapis.com/matrixdock.types.v1.StbtInterestsDistributed";
}
impl ::buffa::Message for StbtInterestsDistributed {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.interest.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.interest) as u64;
        }
        if !self.new_total_supply.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.new_total_supply) as u64;
        }
        if !self.interest_from_time.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.interest_from_time)
                        as u64;
        }
        if !self.interest_to_time.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.interest_to_time) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.interest.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.interest, buf);
        }
        if !self.new_total_supply.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.new_total_supply, buf);
        }
        if !self.interest_from_time.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.interest_from_time, buf);
        }
        if !self.interest_to_time.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.interest_to_time, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(9u32, self.timestamp, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.id, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.interest, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.new_total_supply, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.interest_from_time, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.interest_to_time, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.tx_hash, buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.log_index = ::buffa::types::decode_uint64(buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.block_num = ::buffa::types::decode_uint64(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.timestamp = ::buffa::types::decode_uint64(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.id.clear();
        self.interest.clear();
        self.new_total_supply.clear();
        self.interest_from_time.clear();
        self.interest_to_time.clear();
        self.tx_hash.clear();
        self.log_index = 0u64;
        self.block_num = 0u64;
        self.timestamp = 0u64;
    }
}
