// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct EtherDeposited {
        pub from: Vec<u8>,
        pub amount: substreams::scalar::BigInt,
        pub time: substreams::scalar::BigInt,
    }
    impl EtherDeposited {
        const TOPIC_ID: [u8; 32] = [
            239u8,
            81u8,
            180u8,
            200u8,
            112u8,
            184u8,
            176u8,
            16u8,
            14u8,
            174u8,
            32u8,
            114u8,
            233u8,
            29u8,
            176u8,
            18u8,
            34u8,
            163u8,
            3u8,
            7u8,
            42u8,
            243u8,
            114u8,
            142u8,
            88u8,
            201u8,
            212u8,
            210u8,
            218u8,
            51u8,
            18u8,
            127u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 64usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 64usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 64usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                from: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "from",
                )?,
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
                time: substreams_ethereum::abi::read_uint(log.data(), 32, "time")?,
            })
        }
    }
    impl substreams_ethereum::Event for EtherDeposited {
        const NAME: &'static str = "EtherDeposited";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct TokensBurned {
        pub from: Vec<u8>,
        pub amount: substreams::scalar::BigInt,
        pub eth_amount: substreams::scalar::BigInt,
        pub time: substreams::scalar::BigInt,
    }
    impl TokensBurned {
        const TOPIC_ID: [u8; 32] = [
            25u8,
            120u8,
            59u8,
            52u8,
            88u8,
            145u8,
            96u8,
            193u8,
            104u8,
            72u8,
            125u8,
            199u8,
            249u8,
            197u8,
            26u8,
            224u8,
            188u8,
            239u8,
            230u8,
            122u8,
            71u8,
            214u8,
            112u8,
            143u8,
            186u8,
            144u8,
            246u8,
            206u8,
            3u8,
            102u8,
            211u8,
            209u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 96usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 96usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 96usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                from: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "from",
                )?,
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
                eth_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "eth_amount",
                )?,
                time: substreams_ethereum::abi::read_uint(log.data(), 64, "time")?,
            })
        }
    }
    impl substreams_ethereum::Event for TokensBurned {
        const NAME: &'static str = "TokensBurned";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct TokensMinted {
        pub to: Vec<u8>,
        pub amount: substreams::scalar::BigInt,
        pub eth_amount: substreams::scalar::BigInt,
        pub time: substreams::scalar::BigInt,
    }
    impl TokensMinted {
        const TOPIC_ID: [u8; 32] = [
            97u8,
            85u8,
            207u8,
            208u8,
            253u8,
            2u8,
            139u8,
            12u8,
            167u8,
            126u8,
            132u8,
            149u8,
            166u8,
            12u8,
            190u8,
            86u8,
            62u8,
            139u8,
            206u8,
            134u8,
            17u8,
            240u8,
            170u8,
            214u8,
            254u8,
            219u8,
            218u8,
            175u8,
            192u8,
            93u8,
            68u8,
            162u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 2usize {
                return false;
            }
            if log.data().len() != 96usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 2usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 2usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 96usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 96usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                to: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "to",
                )?,
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
                eth_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "eth_amount",
                )?,
                time: substreams_ethereum::abi::read_uint(log.data(), 64, "time")?,
            })
        }
    }
    impl substreams_ethereum::Event for TokensMinted {
        const NAME: &'static str = "TokensMinted";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}