// @generated by buffa-codegen. DO NOT EDIT.
// source: proto/convex.proto

#[derive(Clone, Debug, Default)]
pub struct EventsView<'a> {
    /// Field 1: `deposited`
    pub deposited: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::DepositedView<'a>,
    >,
    /// Field 2: `withdrawn`
    pub withdrawn: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::WithdrawnView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for EventsView<'a> {
    type Owned = super::super::Events;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::DepositedView>(),
                )?;
                view.deposited
                    .push(
                        <super::super::__buffa::view::DepositedView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::WithdrawnView>(),
                )?;
                view.withdrawn
                    .push(
                        <super::super::__buffa::view::WithdrawnView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Events, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Events {
            deposited: self
                .deposited
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            withdrawn: self
                .withdrawn
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for EventsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.deposited {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        for v in &self.withdrawn {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.deposited {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
        for v in &self.withdrawn {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for EventsView<'a> {
    const PACKAGE: &'static str = "convex.types.v1";
    const NAME: &'static str = "Events";
    const FULL_NAME: &'static str = "convex.types.v1.Events";
    const TYPE_URL: &'static str = "type.googleapis.com/convex.types.v1.Events";
}
::buffa::impl_default_view_instance!(EventsView);
::buffa::impl_view_reborrow!(EventsView);
/** Self-contained, `'static` owned view of a `Events` message.

 Wraps [`::buffa::OwnedView`]`<`[`EventsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`EventsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct EventsOwnedView(::buffa::OwnedView<EventsView<'static>>);
impl EventsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            EventsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Events,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(EventsOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`EventsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &EventsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Events {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `deposited`
    #[must_use]
    pub fn deposited(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::DepositedView<'_>> {
        &self.0.reborrow().deposited
    }
    /// Field 2: `withdrawn`
    #[must_use]
    pub fn withdrawn(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::WithdrawnView<'_>> {
        &self.0.reborrow().withdrawn
    }
}
impl ::core::convert::From<::buffa::OwnedView<EventsView<'static>>> for EventsOwnedView {
    fn from(inner: ::buffa::OwnedView<EventsView<'static>>) -> Self {
        EventsOwnedView(inner)
    }
}
impl ::core::convert::From<EventsOwnedView> for ::buffa::OwnedView<EventsView<'static>> {
    fn from(wrapper: EventsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<EventsView<'static>>>
for EventsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<EventsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Events {
    type View<'a> = EventsView<'a>;
    type ViewHandle = EventsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct DepositedView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `user`
    pub user: &'a str,
    /// Field 3: `pool_id`
    pub pool_id: u64,
    /// Field 4: `amount`
    pub amount: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for DepositedView<'a> {
    type Owned = super::super::Deposited;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.user = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.pool_id = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Deposited, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Deposited, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Deposited {
            id: self.id.to_string(),
            user: self.user.to_string(),
            pool_id: self.pool_id,
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for DepositedView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.user.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.user) as u64;
        }
        if self.pool_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.pool_id) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.user.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.user, buf);
        }
        if self.pool_id != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.pool_id, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for DepositedView<'a> {
    const PACKAGE: &'static str = "convex.types.v1";
    const NAME: &'static str = "Deposited";
    const FULL_NAME: &'static str = "convex.types.v1.Deposited";
    const TYPE_URL: &'static str = "type.googleapis.com/convex.types.v1.Deposited";
}
::buffa::impl_default_view_instance!(DepositedView);
::buffa::impl_view_reborrow!(DepositedView);
/** Self-contained, `'static` owned view of a `Deposited` message.

 Wraps [`::buffa::OwnedView`]`<`[`DepositedView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`DepositedView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct DepositedOwnedView(::buffa::OwnedView<DepositedView<'static>>);
impl DepositedOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            DepositedOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            DepositedOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Deposited,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            DepositedOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`DepositedView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &DepositedView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Deposited {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `user`
    #[must_use]
    pub fn user(&self) -> &'_ str {
        self.0.reborrow().user
    }
    /// Field 3: `pool_id`
    #[must_use]
    pub fn pool_id(&self) -> u64 {
        self.0.reborrow().pool_id
    }
    /// Field 4: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<DepositedView<'static>>>
for DepositedOwnedView {
    fn from(inner: ::buffa::OwnedView<DepositedView<'static>>) -> Self {
        DepositedOwnedView(inner)
    }
}
impl ::core::convert::From<DepositedOwnedView>
for ::buffa::OwnedView<DepositedView<'static>> {
    fn from(wrapper: DepositedOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<DepositedView<'static>>>
for DepositedOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<DepositedView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Deposited {
    type View<'a> = DepositedView<'a>;
    type ViewHandle = DepositedOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct WithdrawnView<'a> {
    /// Field 1: `id`
    pub id: &'a str,
    /// Field 2: `user`
    pub user: &'a str,
    /// Field 3: `pool_id`
    pub pool_id: u64,
    /// Field 4: `amount`
    pub amount: &'a str,
    /// Field 5: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 6: `log_index`
    pub log_index: u64,
    /// Field 7: `block_num`
    pub block_num: u64,
    /// Field 8: `timestamp`
    pub timestamp: u64,
}
impl<'a> ::buffa::MessageView<'a> for WithdrawnView<'a> {
    type Owned = super::super::Withdrawn;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.id = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.user = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.pool_id = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_num = ::buffa::types::decode_uint64(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.timestamp = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Withdrawn, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Withdrawn, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Withdrawn {
            id: self.id.to_string(),
            user: self.user.to_string(),
            pool_id: self.pool_id,
            amount: self.amount.to_string(),
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            block_num: self.block_num,
            timestamp: self.timestamp,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for WithdrawnView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.id) as u64;
        }
        if !self.user.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.user) as u64;
        }
        if self.pool_id != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.pool_id) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if self.block_num != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_num) as u64;
        }
        if self.timestamp != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.timestamp) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.id.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.id, buf);
        }
        if !self.user.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.user, buf);
        }
        if self.pool_id != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.pool_id, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount, buf);
        }
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.log_index, buf);
        }
        if self.block_num != 0u64 {
            ::buffa::types::put_uint64_field(7u32, self.block_num, buf);
        }
        if self.timestamp != 0u64 {
            ::buffa::types::put_uint64_field(8u32, self.timestamp, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for WithdrawnView<'a> {
    const PACKAGE: &'static str = "convex.types.v1";
    const NAME: &'static str = "Withdrawn";
    const FULL_NAME: &'static str = "convex.types.v1.Withdrawn";
    const TYPE_URL: &'static str = "type.googleapis.com/convex.types.v1.Withdrawn";
}
::buffa::impl_default_view_instance!(WithdrawnView);
::buffa::impl_view_reborrow!(WithdrawnView);
/** Self-contained, `'static` owned view of a `Withdrawn` message.

 Wraps [`::buffa::OwnedView`]`<`[`WithdrawnView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`WithdrawnView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct WithdrawnOwnedView(::buffa::OwnedView<WithdrawnView<'static>>);
impl WithdrawnOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            WithdrawnOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            WithdrawnOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Withdrawn,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            WithdrawnOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`WithdrawnView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &WithdrawnView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Withdrawn {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> &'_ str {
        self.0.reborrow().id
    }
    /// Field 2: `user`
    #[must_use]
    pub fn user(&self) -> &'_ str {
        self.0.reborrow().user
    }
    /// Field 3: `pool_id`
    #[must_use]
    pub fn pool_id(&self) -> u64 {
        self.0.reborrow().pool_id
    }
    /// Field 4: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 5: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 6: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 7: `block_num`
    #[must_use]
    pub fn block_num(&self) -> u64 {
        self.0.reborrow().block_num
    }
    /// Field 8: `timestamp`
    #[must_use]
    pub fn timestamp(&self) -> u64 {
        self.0.reborrow().timestamp
    }
}
impl ::core::convert::From<::buffa::OwnedView<WithdrawnView<'static>>>
for WithdrawnOwnedView {
    fn from(inner: ::buffa::OwnedView<WithdrawnView<'static>>) -> Self {
        WithdrawnOwnedView(inner)
    }
}
impl ::core::convert::From<WithdrawnOwnedView>
for ::buffa::OwnedView<WithdrawnView<'static>> {
    fn from(wrapper: WithdrawnOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<WithdrawnView<'static>>>
for WithdrawnOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<WithdrawnView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Withdrawn {
    type View<'a> = WithdrawnView<'a>;
    type ViewHandle = WithdrawnOwnedView;
}
