// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub bancor_network_pool_collection_addeds: ::prost::alloc::vec::Vec<BancorNetworkPoolCollectionAdded>,
    #[prost(message, repeated, tag = "2")]
    pub bancor_network_tokens_tradeds: ::prost::alloc::vec::Vec<BancorNetworkTokensTraded>,
    #[prost(message, repeated, tag = "3")]
    pub pool_collection_tokens_depositeds: ::prost::alloc::vec::Vec<PoolCollectionTokensDeposited>,
    #[prost(message, repeated, tag = "4")]
    pub pool_collection_tokens_withdrawns: ::prost::alloc::vec::Vec<PoolCollectionTokensWithdrawn>,
    #[prost(message, repeated, tag = "5")]
    pub pool_collection_total_liquidity_updateds: ::prost::alloc::vec::Vec<PoolCollectionTotalLiquidityUpdated>,
    #[prost(message, repeated, tag = "6")]
    pub pool_collection_default_trading_fee_ppm_updateds: ::prost::alloc::vec::Vec<PoolCollectionDefaultTradingFeePpmUpdated>,
    #[prost(message, repeated, tag = "7")]
    pub pool_collection_trading_fee_ppm_updateds: ::prost::alloc::vec::Vec<PoolCollectionTradingFeePpmUpdated>,
    #[prost(message, repeated, tag = "8")]
    pub pool_token_factory_pool_token_createds: ::prost::alloc::vec::Vec<PoolTokenFactoryPoolTokenCreated>,
    #[prost(message, repeated, tag = "9")]
    pub network_settings_network_fee_ppm_updateds: ::prost::alloc::vec::Vec<NetworkSettingsNetworkFeePpmUpdated>,
    #[prost(message, repeated, tag = "10")]
    pub network_settings_withdrawal_fee_ppm_updateds: ::prost::alloc::vec::Vec<NetworkSettingsWithdrawalFeePpmUpdated>,
    #[prost(message, repeated, tag = "11")]
    pub standard_rewards_program_createds: ::prost::alloc::vec::Vec<StandardRewardsProgramCreated>,
    #[prost(message, repeated, tag = "12")]
    pub standard_rewards_program_terminateds: ::prost::alloc::vec::Vec<StandardRewardsProgramTerminated>,
    #[prost(message, repeated, tag = "13")]
    pub standard_rewards_program_enableds: ::prost::alloc::vec::Vec<StandardRewardsProgramEnabled>,
    #[prost(message, repeated, tag = "14")]
    pub bnt_pool_tokens_depositeds: ::prost::alloc::vec::Vec<BntPoolTokensDeposited>,
    #[prost(message, repeated, tag = "15")]
    pub bnt_pool_tokens_withdrawns: ::prost::alloc::vec::Vec<BntPoolTokensWithdrawn>,
    #[prost(message, repeated, tag = "16")]
    pub bnt_pool_total_liquidity_updateds: ::prost::alloc::vec::Vec<BntPoolTotalLiquidityUpdated>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BancorNetworkPoolCollectionAdded {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pool_collection: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub log_index: u64,
    #[prost(uint64, tag = "6")]
    pub block_num: u64,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BancorNetworkTokensTraded {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub source_token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub target_token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub source_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub target_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub bnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub target_fee_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub bnt_fee_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub trader: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "12")]
    pub log_index: u64,
    #[prost(uint64, tag = "13")]
    pub block_num: u64,
    #[prost(uint64, tag = "14")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolCollectionTokensDeposited {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub pool_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub log_index: u64,
    #[prost(uint64, tag = "10")]
    pub block_num: u64,
    #[prost(uint64, tag = "11")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolCollectionTokensWithdrawn {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub pool_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub external_protection_base_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub bnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub withdrawal_fee_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "12")]
    pub log_index: u64,
    #[prost(uint64, tag = "13")]
    pub block_num: u64,
    #[prost(uint64, tag = "14")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolCollectionTotalLiquidityUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub evt_pool: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub staked_balance: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub pool_token_supply: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub log_index: u64,
    #[prost(uint64, tag = "10")]
    pub block_num: u64,
    #[prost(uint64, tag = "11")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolCollectionDefaultTradingFeePpmUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub prev_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub new_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub log_index: u64,
    #[prost(uint64, tag = "7")]
    pub block_num: u64,
    #[prost(uint64, tag = "8")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolCollectionTradingFeePpmUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub evt_pool: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub prev_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub new_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub log_index: u64,
    #[prost(uint64, tag = "8")]
    pub block_num: u64,
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolTokenFactoryPoolTokenCreated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub log_index: u64,
    #[prost(uint64, tag = "6")]
    pub block_num: u64,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkSettingsNetworkFeePpmUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub prev_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub log_index: u64,
    #[prost(uint64, tag = "6")]
    pub block_num: u64,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkSettingsWithdrawalFeePpmUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub prev_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_fee_ppm: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub log_index: u64,
    #[prost(uint64, tag = "6")]
    pub block_num: u64,
    #[prost(uint64, tag = "7")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StandardRewardsProgramCreated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub rewards_token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub total_rewards: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub end_time: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub log_index: u64,
    #[prost(uint64, tag = "10")]
    pub block_num: u64,
    #[prost(uint64, tag = "11")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StandardRewardsProgramTerminated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub end_time: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remaining_rewards: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub log_index: u64,
    #[prost(uint64, tag = "8")]
    pub block_num: u64,
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StandardRewardsProgramEnabled {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pool: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub program_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub remaining_rewards: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub log_index: u64,
    #[prost(uint64, tag = "8")]
    pub block_num: u64,
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BntPoolTokensDeposited {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub bnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pool_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub vbnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "8")]
    pub log_index: u64,
    #[prost(uint64, tag = "9")]
    pub block_num: u64,
    #[prost(uint64, tag = "10")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BntPoolTokensWithdrawn {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub bnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pool_token_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub vbnt_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub withdrawal_fee_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "9")]
    pub log_index: u64,
    #[prost(uint64, tag = "10")]
    pub block_num: u64,
    #[prost(uint64, tag = "11")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BntPoolTotalLiquidityUpdated {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub context_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub liquidity: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub staked_balance: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pool_token_supply: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub log_index: u64,
    #[prost(uint64, tag = "8")]
    pub block_num: u64,
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
}
// @@protoc_insertion_point(module)
