// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct PulledElFees {
        pub amount: substreams::scalar::BigInt,
    }
    impl PulledElFees {
        const TOPIC_ID: [u8; 32] = [
            218u8,
            132u8,
            29u8,
            48u8,
            66u8,
            215u8,
            146u8,
            226u8,
            80u8,
            154u8,
            51u8,
            59u8,
            157u8,
            203u8,
            212u8,
            179u8,
            221u8,
            155u8,
            144u8,
            71u8,
            211u8,
            130u8,
            1u8,
            31u8,
            135u8,
            136u8,
            250u8,
            185u8,
            12u8,
            167u8,
            227u8,
            199u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
            })
        }
    }
    impl substreams_ethereum::Event for PulledElFees {
        const NAME: &'static str = "PulledELFees";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct UserDeposit {
        pub depositor: Vec<u8>,
        pub recipient: Vec<u8>,
        pub amount: substreams::scalar::BigInt,
    }
    impl UserDeposit {
        const TOPIC_ID: [u8; 32] = [
            59u8,
            197u8,
            127u8,
            70u8,
            154u8,
            214u8,
            209u8,
            13u8,
            119u8,
            35u8,
            234u8,
            34u8,
            108u8,
            210u8,
            43u8,
            210u8,
            185u8,
            229u8,
            39u8,
            222u8,
            242u8,
            181u8,
            41u8,
            246u8,
            171u8,
            68u8,
            100u8,
            90u8,
            22u8,
            104u8,
            149u8,
            130u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 32usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 32usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 32usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                depositor: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "depositor",
                )?,
                recipient: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "recipient",
                )?,
                amount: substreams_ethereum::abi::read_uint(log.data(), 0, "amount")?,
            })
        }
    }
    impl substreams_ethereum::Event for UserDeposit {
        const NAME: &'static str = "UserDeposit";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}