// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct Deposit {
        pub depositor: Vec<u8>,
        pub deposit_amount: substreams::scalar::BigInt,
        pub minted_amount: substreams::scalar::BigInt,
    }
    impl Deposit {
        const TOPIC_ID: [u8; 32] = [
            144u8,
            137u8,
            8u8,
            9u8,
            198u8,
            84u8,
            241u8,
            29u8,
            110u8,
            114u8,
            162u8,
            143u8,
            166u8,
            1u8,
            73u8,
            119u8,
            10u8,
            13u8,
            17u8,
            236u8,
            108u8,
            146u8,
            49u8,
            157u8,
            108u8,
            235u8,
            43u8,
            176u8,
            164u8,
            234u8,
            26u8,
            21u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 96usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 96usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 96usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                depositor: substreams_ethereum::abi::read_address(
                    log.data(),
                    0,
                    "depositor",
                )?,
                deposit_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "deposit_amount",
                )?,
                minted_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    64,
                    "minted_amount",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for Deposit {
        const NAME: &'static str = "Deposit";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Withdraw {
        pub withdrawer: Vec<u8>,
        pub withdraw_amount: substreams::scalar::BigInt,
        pub burned_amount: substreams::scalar::BigInt,
    }
    impl Withdraw {
        const TOPIC_ID: [u8; 32] = [
            242u8,
            121u8,
            230u8,
            161u8,
            245u8,
            227u8,
            32u8,
            204u8,
            169u8,
            17u8,
            53u8,
            103u8,
            109u8,
            156u8,
            182u8,
            228u8,
            76u8,
            168u8,
            160u8,
            140u8,
            11u8,
            136u8,
            52u8,
            43u8,
            205u8,
            177u8,
            20u8,
            79u8,
            101u8,
            17u8,
            181u8,
            104u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 1usize {
                return false;
            }
            if log.data().len() != 96usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 1usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 1usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 96usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 96usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                withdrawer: substreams_ethereum::abi::read_address(
                    log.data(),
                    0,
                    "withdrawer",
                )?,
                withdraw_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    32,
                    "withdraw_amount",
                )?,
                burned_amount: substreams_ethereum::abi::read_uint(
                    log.data(),
                    64,
                    "burned_amount",
                )?,
            })
        }
    }
    impl substreams_ethereum::Event for Withdraw {
        const NAME: &'static str = "Withdraw";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}